baseurl = "https://oaklandsok.github.io"
languageCode = "en-us"
title = "Systematizing Systematization of Knowledge"
subtitle = ""
theme = "sok"

disableKinds = ["taxonomy"]

[params]
    sidebartitle = "Systematization of Knowledge"
    sidebartagline = "IEEE Symposium on Security and Privacy"
    nodate = true
    noauthor = true
    noread = true
    nopaging=true
    notoc=true

[markup.goldmark.renderer]
unsafe= true



[[menu.main]]

[[menu.footer]]
